version: "2.3"

services:
  deep-learning:
    build: .
    entrypoint: >-
      jupyter lab 
        --allow-root
        --ip=0.0.0.0
        --no-browser
        --NotebookApp.token=''
    volumes:
      - ./src:/dl
      - /data/Project/33.Cytometry:/dl/data
    ports:
      - 11250:8888
    expose:
      - 8888
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    runtime: nvidia
